ticketSystem:
  - type: LOGGER
    properties:
      queue: "monitoring"
      username: "user"
      password: "password"
template:
  subject: '[{{.Status}}] {{index .Labels "alertname"}}'
  bodyFile: message.tpl