ticketSystem:
  - type: LOGGER
    url: https://logger.hook
  - type: ZNOONY
    url: https://znoony.example.com
    properties:
      queue: "monitoring"
      username: "user"
      password: "password"